### ISSUE TITLE
Be nice to support HTTP proxies

### ISSUE THREAD

**Issue by pjakma** [osrg/bgperf#1]
It'd be nice if the docker build of the containers supported passing in a HTTP proxy somehow, for the apt commands, for those behind a corp firewall.

For now I just manually added in ENV http_proxy ... etc to the {bird,exabgp,gobgp,quagga}.py files.

regards,

Paul

**Comment by ishidawataru** [comment]
Hi @pjakma 

Thanks for the feature request!
now supported.
`http_proxy`, `https_proxy` will be reflected in Dockerfiles.
